name: flua
on:
  push:
    branches: [main, develop, feature/*, refactor/*, bugfix/*, hotfix/*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make release
        run: make release
      - name: flua version
        run: ./flua --version
